--------------------------------------------------------
-- Archivo creado  - domingo-agosto-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTE" 
   (	"ID" NUMBER(19,0), 
	"CLIENTE_ID" NUMBER(19,0), 
	"CONTRASEÑA" VARCHAR2(30 CHAR), 
	"ESTADO" NUMBER(1,0), 
	"FK_CLIENTE_PERSONA" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008372
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008372" ON "SYSTEM"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_HDLW0EK681C7BRXD8GCKSYG43
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_HDLW0EK681C7BRXD8GCKSYG43" ON "SYSTEM"."CLIENTE" ("FK_CLIENTE_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENTE" ADD CHECK (estado in (0,1)) ENABLE;
  ALTER TABLE "SYSTEM"."CLIENTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENTE" ADD CONSTRAINT "UK_HDLW0EK681C7BRXD8GCKSYG43" UNIQUE ("FK_CLIENTE_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTE" ADD CONSTRAINT "FKAITDO5PI0NEYH76B0K9P2MJS1" FOREIGN KEY ("FK_CLIENTE_PERSONA")
	  REFERENCES "SYSTEM"."PERSONA" ("ID") ENABLE;
