--------------------------------------------------------
-- Archivo creado  - domingo-agosto-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUENTA" 
   (	"ID" NUMBER(19,0), 
	"NUMERO" VARCHAR2(30 CHAR), 
	"SALDO_INICIAL" NUMBER(10,0), 
	"TIPO" VARCHAR2(30 CHAR), 
	"FK_CUENTA_CLIENTE" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008324
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008324" ON "SYSTEM"."CUENTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("SALDO_INICIAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUENTA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CUENTA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUENTA" ADD CONSTRAINT "FKQM52HFNOA4KOOBQRRLKCGS3U3" FOREIGN KEY ("FK_CUENTA_CLIENTE")
	  REFERENCES "SYSTEM"."CLIENTE" ("ID") ENABLE;
